/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Rubik-Regular"],
        rubik: ["Rubik-Regular"],
        "rubik-light": ["Rubik-Light"],
        "rubik-medium": ["Rubik-Medium"],
        "rubik-bold": ["Rubik-Bold"],
        "rubik-semibold": ["Rubik-SemiBold"],
        "rubik-extrabold": ["Rubik-ExtraBold"],
        "rubik-black": ["Rubik-Black"],
      },
      colors: {
        brand: "#6e11b0",
        "brand-light": "#9333ea",
        "brand-dark": "#4c0b7a",
        accent: "#FF6B35",
        "accent-light": "#FFF0EB",
        like: "#FF4D67",
        repost: "#F59E0B",
        surface: "#FFFFFF",
        background: "#F8F7FA",
        muted: "#9C96AD",
        border: "#E8E6ED",
        text: "#1A1A2E",
        "text-muted": "#6B7280",
        danger: "#EF4444",
        success: "#10B981",
        primary: "#6e11b0",
        secondary: "#9333ea",
      },
    },
  },
  plugins: [],
};
